apiVersion: platform.taskapp.io/v1alpha1
kind: Release
metadata:
  labels:
    app.kubernetes.io/name: release-operator
    app.kubernetes.io/managed-by: kustomize
    platform.taskapp.io/component: checkout
  name: checkout-dev
spec:
  componentRef:
    name: checkout
  environment: dev
  version: 4602f5c24671261337f19b56cea7004d58dd8a2d
  bindings:
    database:
      enabled: true
      ref: checkout-db
